---
title: "Birdsong Overview"
output:
  html_document:
    code_folding: show
    toc: true
    toc_depth: 4
    toc_float: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(cowplot) # version 1.0.0
theme_set(theme_cowplot())
library(formattable)
library(here)
library(gghalves)
library(wesanderson)
```

## Read & Summarize Data

```{r cars}
data <- read.csv(here("processed_data","Birdsong_data.csv"))

subj_summary <- data %>%
  filter(subj_exclusion=="no") %>%
  filter(trial_exclusion=="no") %>%
  group_by(subjCode,Days,gender,version,audioType) %>%
  summarize(
    N = n(),
    mean_looking_time = mean(looking_time),
    sd_looking_time = sd(looking_time)
  )
```

## Overall Looking

Table of overall looking behavior by group and experiment

```{r}
overall_summary <- subj_summary %>%
  group_by(version,audioType) %>%
  summarize(
    N=n(),
    mean_age_days = mean(Days),
    num_female=sum(gender=="f"),
    mean_looking_ms = mean(mean_looking_time),
    sd_looking_ms = sd(mean_looking_time),
    ci_looking_ms = qt(0.975, N-1)*sd_looking_ms/sqrt(N)
  )
overall_summary %>%
  formattable()
```

## Plot

Plot overall results

```{r, warning=FALSE}
pal <- wes_palette("Rushmore1", n=5)
ggplot(subj_summary,aes(x=audioType,y=mean_looking_time, color=audioType,fill=audioType))+
  geom_violin(trim=F,alpha=0.5)+
  geom_line(aes(group=subjCode),color="black",fill=NA,alpha=0.2,size=0.75,position=position_jitter(width=0.05,seed=1))+
  geom_point(aes(group=subjCode), size = 2.5, alpha=0.5,position=position_jitter(width=0.05,seed=1))+
  geom_point(data=overall_summary,aes(y=mean_looking_ms),color="black",size=5)+
  geom_line(data=overall_summary,aes(y=mean_looking_ms,group=1),color="black",size=1.3)+
  geom_errorbar(data=overall_summary,aes(y=mean_looking_ms,ymin=mean_looking_ms-ci_looking_ms,ymax=mean_looking_ms+ci_looking_ms),width=0,color="black")+
  scale_colour_manual(values=pal[c(2,3,4)])+
  scale_fill_manual(values=pal[c(2,3,4)])+
  facet_wrap(.~version)+
  theme(legend.position="none")+
  xlab("Stimulus Type")+
  ylab("Looking Time (in ms)")+
  theme(axis.title.x = element_text(face="bold", size=20),
        axis.text.x  = element_text(size=16,angle=90),
        axis.title.y = element_text(face="bold", size=20),
        axis.text.y  = element_text(size=16),
        strip.text.x = element_text(size = 16,face="bold")
        )
```
